import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Navbar";
import { AuthContextProvider } from "./context/firebase";
import { HeroUIProvider, ToastProvider } from "@heroui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <HeroUIProvider>
            <ToastProvider placement="bottom-center" toastOffset={10} />

            <Nav />
            {children}
          </HeroUIProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
